databases:
  - name: djangobackenddb
    plan: free
    databaseName: djangobackend
    user: djangobackend

services:
  - type: web
    plan: free
    name: djangobackend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd djangoback && python -m gunicorn djangoback.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djangobackenddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4