# Generated by Django 5.1.2 on 2024-10-27 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_transit', 'In Transit'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('fuel_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_tracked_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_load_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_load_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
